server:
  port: 8091

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://host.docker.internal:5432/heatmap_db"  # Connect to host's PostgreSQL
    # url: "jdbc:postgresql://postgres-container:5432/heatmap_db"  # For container-to-container
    # url: "jdbc:postgresql://localhost:5432/heatmap_db"  # This points to container's localhost
    username: "postgres"
    password: "admin1234"
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
  data:
    redis:
      host: redis-container
      # host: localhost
      port: 6379